#!/bin/bash

# install packages
apt-get update && apt-get upgrade -y --no-install-recommends \
  bc \
  bison \
  build-essential \
  cpio \
  cscope \
  exuberant-ctags \
  flex \
  gcc \
  libssl-dev \
  minicom \
  rsync \
  software-properties-common \
  tig
