# Dockerfile
FROM how2flow/workspace:base

ENV ID="tags"

USER root
WORKDIR /root
COPY fixups fixups
RUN chmod -R +x fixups
RUN ./fixups/pkg
# RUN ./fixups/..
RUN ./id $ID
RUN ./sudo $ID
RUN rm -rf fixups id sudo

USER ${ID}
WORKDIR /home/${ID}
# user fixups ...
