# Dockerfile

# ===== No Edit =====
FROM how2flow/workspace:base
# ===================

ENV ID="tags"

# ===== No Edit =====
USER root
WORKDIR /root
COPY fixups fixups
RUN chmod -R +x fixups
# ===================

# ===== No Edit =====
WORKDIR /root/fixups
RUN ./postfix $ID
# ===================
# TODO ...
#
# ===== No Edit =====
RUN rm -rf fixups
# ===================

# ===== No Edit =====
USER ${ID}
WORKDIR /home/${ID}
# ===================
# TODO ...
