#!/bin/bash

# author: "steve.jeong"
# e-mail: "how2soft@gmail.com"
# date: 2022.11.10

# vars
BACKUP_DIR=${TOP_DIR}/backups
INSTALL_DIR=${TOP_DIR}/install

default_options() {
  local foo=""

  foo=$(cat /etc/*-release | grep CODENAME)
  DISTRO=${foo##*=}
  case ${DISTRO} in
    bionic | focal | jammy)
      OS=ubuntu
      ;;
    buster | bullseye | bookworm)
      OS=debian
      ;;
  esac
  [ -z ${FLAVOUR} ] && FLAVOUR="server"
  [ -z ${NAME} ] && NAME="base"
  [ -z ${SPEED} ] && SPEED="1"
  [ -z ${TARGET} ] && TARGET="vi"
  [ -z ${VERSION} ] && VERSION="None"
}

print_env() {

  default_options

  echo "@@@ workspace setting script @@@"
  echo "Author:steve.jeong"
  echo "E-mail:how2soft@gmail.com"
  echo "date: ${TIME}"
  echo ""

  echo "====== ENV. ======"
  echo "OS=${OS}"
  echo "DISTRO=${DISTRO}"
  echo "===== PARAMS ====="
  echo "NAME=${NAME}"
  echo "SPEED=${SPEED}"
  echo "TARGET=${TARGET}"
  echo "VERSION=${VERSION}"
  echo "=================="
  echo ""

}
