#!/bin/bash

# Author: steve.jeong
# e-mail: jkhpro1003@gmail.com
# start: 2022.10.24
# last-modified: 2022.11.10

set -e

# directories
TOP_DIR="$(cd $(dirname $0); pwd -P )"

usage() {
  echo "Usage: $(basename $0) [--help] [--target=<env>]"
  echo "          [--version=<target version>]"
  echo "          [--name=<name>]"
  echo ""
  echo ""
  echo "    ===== options ====="
  echo "    --help: print usage"
  echo "    --target=<env>: select setting env"
  echo "    --version=<target version>: target's version"
  echo "                  e.g. python\"3.6\""
  echo "    --name=<name>: output name"
  echo "    ==================="
  echo ""
  echo "    e.g. setting \"vi\" env"
  echo ""
  echo "    $ cd workspace"
  echo "    $ ./set --target=vi"
  exit 0
}

# option parsing
for opt in $@; do
  case ${opt} in
    --help)
      usage
      ;;
    --flavour=*)
      FLAVOUR=${opt#*=}
      ;;
    --name=*)
      NAME=${opt#*=}
      ;;
    --speed=*)
      SPEED=${opt#*=}
      ;;
    --target=*)
      TARGET=${opt#*=}
      ;;
    --version=*)
      VERSION=${opt#*=}
      ;;
    *)
      echo "Invalid option"
      ;;
  esac
done

. ${TOP_DIR}/time
. ${TOP_DIR}/prefix
. ${TOP_DIR}/functions

print_env
do_preinstall
if [ -d ${BACKUP_DIR} ]; then
  echo "===== WARNING! There are backup files already. ====="
  confirm "Do you still want to proceed with the backup? (Y/n)?" \
    && do_backup
else
  do_backup
fi
echo "[INFO] complete backup before setting workspace."
do_install

# vim: set ft=sh ts=4 sw=2 sts=2 et
