version: '3'

volumes:
  bootloader: {}
  kernel: {}
  share_data: {}

services:
  workspace:
    image: how2flow/workspace:latest
    container_name: work-latest
    stdin_open: true
    tty: true
#   devices:
#     - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - bootloader:/var/lib/bootloader
      - kernel:/var/lib/kernel
      - share_data:/var/lib/share_data
    environment:
      - PYTHONUNBUFFERED=0

# docker compose up -d
# docker attach work-latest
