#!/bin/bash

# set ssh-rsa after install packages. (ubuntu 22.04 ~)
# written by how2flow(Steve Jeong).

SSH_CONF="/etc/ssh"
SSH_CONF_FILE="/etc/ssh/ssh_config"

# for ssh-rsa
if [ -d "${SSH_CONF}" ]; then
  echo "    HostKeyAlgorithms +ssh-rsa" >> "${SSH_CONF_FILE}"
  echo "    PubkeyAcceptedKeyTypes +ssh-rsa" >> "${SSH_CONF_FILE}"
fi

echo "Finish ssh configs"
