#!/bin/bash

apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  fonts-nanum \
  git \
  libssl-dev \
  rsync \
  ruby \
  ruby-dev \
  software-properties-common \
  ssh \
  sudo \
  tig \
  tmux \
  vim \
  wget
