version: '3'

volumes:
  share_data: {}
  kernel: {}

services:
  workspace:
    image: how2flow/workspace:jekyll
    container_name: work-jekyll
    stdin_open: true
    tty: true
    volumes:
      - share_data:/var/lib/share_data
    environment:
      - PYTHONUNBUFFERED=0
    ports:
      - 4000:4000

# docker compose up -d
# docker attach work-focal
