#!/bin/bash

set -e

# sudo apt update
# sudo apt-get install docker-compose-plugin

COMPOSE="$(cd $(dirname $0); pwd -P)/docker-compose.yaml"
PROJECT="workspace"
TAG=${1:-latest}
VOLUMES=("/mnt/docker/${PROJECT}/${TAG}/bootloader"
         "/mnt/docker/${PROJECT}/${TAG}/kernel"
         "/mnt/docker/${PROJECT}/${TAG}/share_data")

if [ $EUID != 0 ]; then
  echo "Run with root permission"
  exit 0
fi

if [ -z "$(command -v docker)" ]; then
  echo "You need to install docker"
fi

for volume in ${VOLUMES[@]}; do
  if [ ! -d ${volume} ]; then
    mkdir -p ${volume}
  fi
done

CONTAINER_NAME="work-${TAG}"

if [ -e ${COMPOSE} ]; then
  cat ${COMPOSE} > ${COMPOSE}.old
  cat <<__EOF > ${COMPOSE}
version: '3'

services:
  ${PROJECT}:
    image: how2flow/${PROJECT}:${TAG}
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /mnt/docker/${PROJECT}/${TAG}/bootloader:/var/lib/bootloader
      - /mnt/docker/${PROJECT}/${TAG}/kernel:/var/lib/kernel
      - /mnt/docker/${PROJECT}/${TAG}/share_data:/var/lib/share_data
    environment:
      - PYTHONUNBUFFERED=0
__EOF

docker compose up -d
fi

