# Dockerfile

# ===== No Edit =====
FROM how2flow/config:ubuntu
# ===================

ENV ID="tags"

# ===== No Edit =====
USER root
WORKDIR /root
COPY fixups fixups
RUN chmod -R +x fixups
# ===================

# ===== No Edit =====
WORKDIR /root/fixups
RUN ./postfix $ID $PASSWORD
# ===================
# TODO ...
# ===== No Edit =====
RUN rm -rf fixups
# ===================

# ===== No Edit =====
USER ${ID}
WORKDIR /home/${ID}
RUN vim +PluginInstall +qall
# ===================
# TODO ...
