#!/bin/bash


SETUP_LIST=(
  "cancel"
  "tcc897x"
  "tcc803x"
  "tcc805x"
  "tcc807x"
  "tcn100x"
)
IDX=0

echo "setup target board"
for list in ${SETUP_LIST[@]}; do
  echo "[${IDX}] ${list}"
  IDX=$((${IDX} + 1))
done

read -p "select target board: " target
case ${target} in
  0)
    echo "Canceled"
    ;;
  1)
    . setup-${SETUP_LIST[1]}.sh
    ;;
  2)
    . setup-${SETUP_LIST[2]}.sh
    ;;
  3)
    . setup-${SETUP_LIST[3]}.sh
    ;;
  4)
    . setup-${SETUP_LIST[4]}.sh
    ;;
  5)
    . setup-${SETUP_LIST[5]}.sh
    ;;
  *)
    echo "Invalid Value"
    ;;
esac
