#!/bin/bash

set_config() {
  local conf_list=""

  conf_list=($(ls ${SET_CFG_DIR}))
  for idx in ${conf_list[@]}; do
    sudo cp ${SET_CFG_DIR}/${idx} ${HOME}/.${idx}
    echo ${idx} >> ${TMP_CFG_LIST}
  done
  update_history "===== setup ====="

  echo "configure setting..."
}

set_config

echo "[C] configure... OK"
