#!/bin/bash

apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  fonts-nanum \
  libssl-dev \
  rsync \
  ruby \
  ruby-dev \
  software-properties-common \
  tig

gem install bundler
