name: 'docker-focal (CI/CD)'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'docker/focal/*'
    tags-ignore:
      - 'v2.0.*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/Checkout@v3

      - name: 'Docker upload'
        uses: how2flow/upload-docker-action@v1
        with:
          context: 'docker/focal'
          repository: 'workspace'
          release: 'focal'
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
